import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "on-error": "#690005",
        "on-secondary-fixed": "#180065",
        "surface-tint": "#3cd7ff",
        "on-primary-container": "#00586b",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-container": "#005d27",
        "on-secondary-container": "#b8afff",
        tertiary: "#66fa8c",
        "on-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "tertiary-container": "#45dd73",
        surface: "#131313",
        "surface-bright": "#3a3939",
        "on-surface-variant": "#bbc9cf",
        "outline-variant": "#3c494e",
        "inverse-primary": "#00677e",
        "on-primary-fixed-variant": "#004e5f",
        "on-primary-fixed": "#001f27",
        "surface-dim": "#131313",
        "surface-container-low": "#1c1b1b",
        secondary: "#c7bfff",
        "surface-container-highest": "#353534",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        error: "#ffb4ab",
        "primary-fixed": "#b4ebff",
        "on-secondary": "#2b009e",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#005321",
        "secondary-container": "#442bbd",
        "secondary-fixed": "#e4deff",
        "on-error-container": "#ffdad6",
        primary: "#a8e8ff",
        "secondary-fixed-dim": "#c7bfff",
        "inverse-on-surface": "#313030",
        outline: "#859398",
        "tertiary-fixed": "#6bff8f",
        "primary-fixed-dim": "#3cd7ff",
        "on-tertiary-fixed": "#002109",
        "primary-container": "#00d4ff",
        "tertiary-fixed-dim": "#4ae176",
        "on-tertiary": "#003915",
        "on-secondary-fixed-variant": "#4228bb",
        "on-primary": "#003642"
      },
    },
  },
  plugins: [],
};
export default config;
